.TH P11\-KIT\-REMOTE@.SERVICE 5 2017\-04\-09 p11\-remote
.SH NAME
p11\-kit\-remote@.service \- PKCS#11 remoting socket
.SH SYNOPSIS
.B p11\-kit\-remote@.service
.SH DESCRIPTION
A socket activated PKCS#11 remote access server.
.SH SEE ALSO
.BR p11\-kit\-remote.socket (5),
.BR libp11\-kit\-engine.so (1),
.BR p11\-kit (8)
.SH AUTHORS
Lubomir Rintel
